//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputMaps/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""b0c6a23a-fd0d-4754-ae78-2216f10c84c0"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""a6481489-3542-47ff-b91e-972946ba286c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Sacrifice"",
                    ""type"": ""Button"",
                    ""id"": ""4871a70e-2036-4041-b4a3-f9b4a4ea762f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseMovement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""1af83a26-ec88-430c-8ae0-c864e1f6f7c9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GamepadCursorMove"",
                    ""type"": ""PassThrough"",
                    ""id"": ""e96a9402-4550-4d5d-8f59-d8a39feec0e4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleSummon"",
                    ""type"": ""Button"",
                    ""id"": ""817b2bd9-269c-46c6-8dd6-f33971b616b8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Summon"",
                    ""type"": ""Button"",
                    ""id"": ""c581cf39-75ae-4de9-ad96-bc506df56d12"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleUp"",
                    ""type"": ""Button"",
                    ""id"": ""a3b358c2-afd0-4765-95d1-888437c43185"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleDown"",
                    ""type"": ""Button"",
                    ""id"": ""ecaece93-4d1d-4bb5-aff7-d51c014996a3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TogglePause"",
                    ""type"": ""Button"",
                    ""id"": ""d88f5e91-cd7f-40ae-95f9-9ccbd31cc7f6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""71ddc4e1-4b45-42ab-aa9b-3ce9f1daec78"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7043dc1b-3d2b-4b9c-a265-90b500cabc44"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ea9e4eac-2a1d-4437-ac33-1cc13609be58"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""03e03841-58ab-4617-b4ea-8f51498160bb"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a2e85e42-1504-4087-b834-b52952970046"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""ARROW"",
                    ""id"": ""b44470b5-3c43-4f8a-b6eb-847d4daf3b6b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""454a91e5-e8f1-4ed1-a800-7eeb18a48adb"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0beca2d1-4a39-4cc8-8d1d-9a1a647872b0"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""79fae11e-88c7-4daf-b8f7-8878d3bd7140"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3d0927d2-3c43-4644-a802-ae313ef281c4"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Controller"",
                    ""id"": ""ebb187d8-c84f-4ac1-8ae1-706acbdb55c3"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""fabf55a2-5662-455b-adb9-eddcd1c06b63"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""41a41dbd-628e-4f2a-90c0-12977b9f6911"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5182e9d5-5c54-44b0-b7a3-af103b7e8975"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ef012a9f-55a8-467a-a5b0-ef215e10cf8a"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""537f9f89-7763-4515-aee7-bd26692fd281"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sacrifice"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""097d97eb-9268-431d-b6bd-b12e4e8cd8e4"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sacrifice"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd4f4b29-68d0-4636-afa4-20706275102c"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1ccb66ac-8866-4a35-abb3-0502d148f941"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GamepadCursorMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8fd94b90-6296-4e0d-b54a-2285cd9de55d"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleSummon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46fac143-a597-4b31-a4ef-392af3c38c5b"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Summon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf5dd506-18a4-4f01-b45f-375a94f185d2"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Summon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""806a5999-f0a5-4907-8931-3adec501c9b9"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""23742eec-e95e-4ea2-9c99-de305fc0c571"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e2dec1d-94fe-40d3-ac62-12b276cf0713"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TogglePause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e222867-6c8d-4526-b75d-a86bca79c314"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TogglePause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Menu"",
            ""id"": ""188efc5d-fe36-4b75-bbd6-b4c71b96c049"",
            ""actions"": [
                {
                    ""name"": ""PowerUp_1"",
                    ""type"": ""Button"",
                    ""id"": ""67431d37-b8ae-4d24-b620-1911dd7cfd7e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PowerUp_2"",
                    ""type"": ""Button"",
                    ""id"": ""25421d9b-c35f-491c-b47a-e952d7983d3e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PowerUp_3"",
                    ""type"": ""Button"",
                    ""id"": ""80819b00-f3bf-476e-992c-ef7ea88f6376"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MainMenu"",
                    ""type"": ""Button"",
                    ""id"": ""2d719eb9-c250-44e5-a4d3-0d0c4a3a7488"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Replay"",
                    ""type"": ""Button"",
                    ""id"": ""e43ee5bd-b54b-4c12-9590-b605fd4e29bd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6cd8edae-ab6c-4753-b91a-b9897703b6a2"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PowerUp_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5279db1-9105-4644-ad4a-c6aae2b82960"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PowerUp_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a599b40e-1d13-4a13-b54c-15b5436ba80f"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PowerUp_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00341bb3-d04d-4e5b-bd59-33feb5b0f250"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MainMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00877f00-d9f4-4230-891f-070f9fa34bea"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Replay"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player_Sacrifice = m_Player.FindAction("Sacrifice", throwIfNotFound: true);
        m_Player_MouseMovement = m_Player.FindAction("MouseMovement", throwIfNotFound: true);
        m_Player_GamepadCursorMove = m_Player.FindAction("GamepadCursorMove", throwIfNotFound: true);
        m_Player_ToggleSummon = m_Player.FindAction("ToggleSummon", throwIfNotFound: true);
        m_Player_Summon = m_Player.FindAction("Summon", throwIfNotFound: true);
        m_Player_ToggleUp = m_Player.FindAction("ToggleUp", throwIfNotFound: true);
        m_Player_ToggleDown = m_Player.FindAction("ToggleDown", throwIfNotFound: true);
        m_Player_TogglePause = m_Player.FindAction("TogglePause", throwIfNotFound: true);
        // Menu
        m_Menu = asset.FindActionMap("Menu", throwIfNotFound: true);
        m_Menu_PowerUp_1 = m_Menu.FindAction("PowerUp_1", throwIfNotFound: true);
        m_Menu_PowerUp_2 = m_Menu.FindAction("PowerUp_2", throwIfNotFound: true);
        m_Menu_PowerUp_3 = m_Menu.FindAction("PowerUp_3", throwIfNotFound: true);
        m_Menu_MainMenu = m_Menu.FindAction("MainMenu", throwIfNotFound: true);
        m_Menu_Replay = m_Menu.FindAction("Replay", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player_Sacrifice;
    private readonly InputAction m_Player_MouseMovement;
    private readonly InputAction m_Player_GamepadCursorMove;
    private readonly InputAction m_Player_ToggleSummon;
    private readonly InputAction m_Player_Summon;
    private readonly InputAction m_Player_ToggleUp;
    private readonly InputAction m_Player_ToggleDown;
    private readonly InputAction m_Player_TogglePause;
    public struct PlayerActions
    {
        private @PlayerInput m_Wrapper;
        public PlayerActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @Sacrifice => m_Wrapper.m_Player_Sacrifice;
        public InputAction @MouseMovement => m_Wrapper.m_Player_MouseMovement;
        public InputAction @GamepadCursorMove => m_Wrapper.m_Player_GamepadCursorMove;
        public InputAction @ToggleSummon => m_Wrapper.m_Player_ToggleSummon;
        public InputAction @Summon => m_Wrapper.m_Player_Summon;
        public InputAction @ToggleUp => m_Wrapper.m_Player_ToggleUp;
        public InputAction @ToggleDown => m_Wrapper.m_Player_ToggleDown;
        public InputAction @TogglePause => m_Wrapper.m_Player_TogglePause;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Sacrifice.started += instance.OnSacrifice;
            @Sacrifice.performed += instance.OnSacrifice;
            @Sacrifice.canceled += instance.OnSacrifice;
            @MouseMovement.started += instance.OnMouseMovement;
            @MouseMovement.performed += instance.OnMouseMovement;
            @MouseMovement.canceled += instance.OnMouseMovement;
            @GamepadCursorMove.started += instance.OnGamepadCursorMove;
            @GamepadCursorMove.performed += instance.OnGamepadCursorMove;
            @GamepadCursorMove.canceled += instance.OnGamepadCursorMove;
            @ToggleSummon.started += instance.OnToggleSummon;
            @ToggleSummon.performed += instance.OnToggleSummon;
            @ToggleSummon.canceled += instance.OnToggleSummon;
            @Summon.started += instance.OnSummon;
            @Summon.performed += instance.OnSummon;
            @Summon.canceled += instance.OnSummon;
            @ToggleUp.started += instance.OnToggleUp;
            @ToggleUp.performed += instance.OnToggleUp;
            @ToggleUp.canceled += instance.OnToggleUp;
            @ToggleDown.started += instance.OnToggleDown;
            @ToggleDown.performed += instance.OnToggleDown;
            @ToggleDown.canceled += instance.OnToggleDown;
            @TogglePause.started += instance.OnTogglePause;
            @TogglePause.performed += instance.OnTogglePause;
            @TogglePause.canceled += instance.OnTogglePause;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Sacrifice.started -= instance.OnSacrifice;
            @Sacrifice.performed -= instance.OnSacrifice;
            @Sacrifice.canceled -= instance.OnSacrifice;
            @MouseMovement.started -= instance.OnMouseMovement;
            @MouseMovement.performed -= instance.OnMouseMovement;
            @MouseMovement.canceled -= instance.OnMouseMovement;
            @GamepadCursorMove.started -= instance.OnGamepadCursorMove;
            @GamepadCursorMove.performed -= instance.OnGamepadCursorMove;
            @GamepadCursorMove.canceled -= instance.OnGamepadCursorMove;
            @ToggleSummon.started -= instance.OnToggleSummon;
            @ToggleSummon.performed -= instance.OnToggleSummon;
            @ToggleSummon.canceled -= instance.OnToggleSummon;
            @Summon.started -= instance.OnSummon;
            @Summon.performed -= instance.OnSummon;
            @Summon.canceled -= instance.OnSummon;
            @ToggleUp.started -= instance.OnToggleUp;
            @ToggleUp.performed -= instance.OnToggleUp;
            @ToggleUp.canceled -= instance.OnToggleUp;
            @ToggleDown.started -= instance.OnToggleDown;
            @ToggleDown.performed -= instance.OnToggleDown;
            @ToggleDown.canceled -= instance.OnToggleDown;
            @TogglePause.started -= instance.OnTogglePause;
            @TogglePause.performed -= instance.OnTogglePause;
            @TogglePause.canceled -= instance.OnTogglePause;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // Menu
    private readonly InputActionMap m_Menu;
    private List<IMenuActions> m_MenuActionsCallbackInterfaces = new List<IMenuActions>();
    private readonly InputAction m_Menu_PowerUp_1;
    private readonly InputAction m_Menu_PowerUp_2;
    private readonly InputAction m_Menu_PowerUp_3;
    private readonly InputAction m_Menu_MainMenu;
    private readonly InputAction m_Menu_Replay;
    public struct MenuActions
    {
        private @PlayerInput m_Wrapper;
        public MenuActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @PowerUp_1 => m_Wrapper.m_Menu_PowerUp_1;
        public InputAction @PowerUp_2 => m_Wrapper.m_Menu_PowerUp_2;
        public InputAction @PowerUp_3 => m_Wrapper.m_Menu_PowerUp_3;
        public InputAction @MainMenu => m_Wrapper.m_Menu_MainMenu;
        public InputAction @Replay => m_Wrapper.m_Menu_Replay;
        public InputActionMap Get() { return m_Wrapper.m_Menu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuActions set) { return set.Get(); }
        public void AddCallbacks(IMenuActions instance)
        {
            if (instance == null || m_Wrapper.m_MenuActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MenuActionsCallbackInterfaces.Add(instance);
            @PowerUp_1.started += instance.OnPowerUp_1;
            @PowerUp_1.performed += instance.OnPowerUp_1;
            @PowerUp_1.canceled += instance.OnPowerUp_1;
            @PowerUp_2.started += instance.OnPowerUp_2;
            @PowerUp_2.performed += instance.OnPowerUp_2;
            @PowerUp_2.canceled += instance.OnPowerUp_2;
            @PowerUp_3.started += instance.OnPowerUp_3;
            @PowerUp_3.performed += instance.OnPowerUp_3;
            @PowerUp_3.canceled += instance.OnPowerUp_3;
            @MainMenu.started += instance.OnMainMenu;
            @MainMenu.performed += instance.OnMainMenu;
            @MainMenu.canceled += instance.OnMainMenu;
            @Replay.started += instance.OnReplay;
            @Replay.performed += instance.OnReplay;
            @Replay.canceled += instance.OnReplay;
        }

        private void UnregisterCallbacks(IMenuActions instance)
        {
            @PowerUp_1.started -= instance.OnPowerUp_1;
            @PowerUp_1.performed -= instance.OnPowerUp_1;
            @PowerUp_1.canceled -= instance.OnPowerUp_1;
            @PowerUp_2.started -= instance.OnPowerUp_2;
            @PowerUp_2.performed -= instance.OnPowerUp_2;
            @PowerUp_2.canceled -= instance.OnPowerUp_2;
            @PowerUp_3.started -= instance.OnPowerUp_3;
            @PowerUp_3.performed -= instance.OnPowerUp_3;
            @PowerUp_3.canceled -= instance.OnPowerUp_3;
            @MainMenu.started -= instance.OnMainMenu;
            @MainMenu.performed -= instance.OnMainMenu;
            @MainMenu.canceled -= instance.OnMainMenu;
            @Replay.started -= instance.OnReplay;
            @Replay.performed -= instance.OnReplay;
            @Replay.canceled -= instance.OnReplay;
        }

        public void RemoveCallbacks(IMenuActions instance)
        {
            if (m_Wrapper.m_MenuActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMenuActions instance)
        {
            foreach (var item in m_Wrapper.m_MenuActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MenuActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MenuActions @Menu => new MenuActions(this);
    public interface IPlayerActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnSacrifice(InputAction.CallbackContext context);
        void OnMouseMovement(InputAction.CallbackContext context);
        void OnGamepadCursorMove(InputAction.CallbackContext context);
        void OnToggleSummon(InputAction.CallbackContext context);
        void OnSummon(InputAction.CallbackContext context);
        void OnToggleUp(InputAction.CallbackContext context);
        void OnToggleDown(InputAction.CallbackContext context);
        void OnTogglePause(InputAction.CallbackContext context);
    }
    public interface IMenuActions
    {
        void OnPowerUp_1(InputAction.CallbackContext context);
        void OnPowerUp_2(InputAction.CallbackContext context);
        void OnPowerUp_3(InputAction.CallbackContext context);
        void OnMainMenu(InputAction.CallbackContext context);
        void OnReplay(InputAction.CallbackContext context);
    }
}
